server:
  port: 8084

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/file-storage-db
    username: user
    password: password

  datasource:
    url: jdbc:mysql://localhost:3306/file-storage-db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://localhost:3306/file-storage-db
    user: user
    password: password
    locations: classpath:db/migration
    enabled: true